.so macros

.TL
My first groff document
.AU
Tomasz Marx
.AI
LO2 Opole
.AS
This is an abstract AS.

.PP
This is a paragraph.
Lorem.
Ipsum.

asdf
.PP
Another paragraph.
.NH 1
Second section
.NH 2
Subsection
.NH 2
Another subsection

.PP
This is a sentence. I want the word
.B "bold"
to be bold.
We can have
.I "italic text"
with .I.
.BI "This is bold italic text"
.RS
.PP
This is a sentence. I want the word
.B "bold"
to be bold.
We can have
.I "italic text"
with .I.
.BI "This is bold italic text"
.RE
.PP
This is a sentence. I want the word
.B "bold"
to be bold.
We can have
.I "italic text"
with .I.
.BI "This is bold italic text"

.PP
The last word of this sentence is
.B "bold" !
The last word of this sentence is
.B "bold" ). (
The things we can do is
.UL "underline text" ,
.BX "boxed text"

.SH
Macros
.IP \(bu 2
This is a list item
.IP \(bu
Another one
.SH
Here is a break
.BL
This is a bulleted item
.BL
here is another

