#![feature(asm)]

use std::time::Instant;

fn main() {
    let now = Instant::now();

    for _ in 0..1000 {
    unsafe {
        asm!("
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            inc rbx
            ",
            out("rbx") _,
            options(nostack, nomem)
        )
    }
    }

    println!("{:?}", now.elapsed());
}
